### ISSUE TITLE
Do not see the Addins 

### ISSUE THREAD

**Issue by jystatistics** [ThinkR-open/remedy#42]
Hi,

Thank you for developing the package. 

I installed remedy package and closed my RStudio and reopen the program. However, I do not see the Addins function in my program. 

<img width="1427" alt="screen shot 2018-11-02 at 11 58 16 am" src="https://user-images.githubusercontent.com/39386861/47929466-147d8b00-de97-11e8-8c8e-864a23812522.png">

Could you hep on this? Thank you.

**Comment by yonicd** [comment]
Please paste in the output from sessioninfo::session_info()

**Comment by ColinFay** [comment]
Hey @jystatistics, 

Let's start with the simplest question first: have you scrolled down the addin list? 

What happens if you try to search for a remedy function in the search area (like, "Blockquote" for example)? 

Do you seen remedy available in the keyboard shortcuts panel?
Tools > Modify Keyboard Shortcut > and search for "blockquote". 

<img width="732" alt="screenshot 2018-11-02 at 21 43 13" src="https://user-images.githubusercontent.com/17936236/47939667-6ac6ea00-dee8-11e8-8323-82198ad03a38.png">

**Comment by statnmap** [comment]
There has been no reply for almost a year.  
I close this issue.
